name = "fivem-map"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "fivem-map-db"
database_id = "0e2b7c28-0029-42bb-82e3-2df77f8879d9"

[[r2_buckets]]
binding = "R2"
bucket_name = "fivem-map-uploads"
